AWSTemplateFormatVersion: "2010-09-09"
Description: Create dms full load cronjob using eventbridge and lambda

Parameters:
  DMSTaskArn:
    Type: String
    Default: ''
    Description: 'the list of the full load task, seperated with ,'

  ScheduledTime:
    Type: String
    Default: 'cron(0 12 * * ? *)'
    AllowedValues:
      - 'cron(0 12 * * ? *)'
      - 'every day 0 am '
      - 'every 1 hour'
      - 'every 12 hours'
      - 'every 24 hours'
    Description: 'the time of the recurred event: cron(0 12 * * ? *) 
                  Sample: '

  LambdaDMSCronJobFunctionName:
    Type: String
    Description: Name of the lambda function
    Default: aws-dms-cronjob-function

  EventBridgeScheduledEventName:
    Type: String
    Description: Name of the EventBridge Rules
    Default: aws-dms-cronjob-event-name

  IAMDMSCronJobRoleName:
    Type: String
    Description: IAM role name for lambda
    Default: aws-dms-cronjob-role

  IAMDMSCronJobPolicyName:
    Type: String
    Description: IAM customed managed policy
    Default: aws-dms-cronjob-policy

Resources:
  # Lambda functions resources
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Ref IAMDMSCronJobPolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  # DMS permissions
                  - 'dms:StartReplicationTask'
                  - 'dms:DescribeReplicationTasks'

                  # CloudWatch permissions
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'

                Resource: '*'

  LambdaDMSCronJob:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn 
      Code:
        ZipFile: |
              import json
              import boto3
              import os

              def lambda_handler(event, context):
                  print("Cron job trigger")
                  # print time and trigger type

                  _dms_tasks_list = os.environ['dms_tasks'].split(',')

                  client = boto3.client('dms')
                  for _task in _dms_tasks_list:
                      # retrieve the replication task's status
                      _task = _task.strip()
                      _replication_task = client.describe_replication_tasks(
                              Filters=[
                                  {
                                      'Name': 'replication-task-arn',
                                      'Values': [_task]
                                  },
                              ],
                              WithoutSettings=True|False
                      )
                      _load_type = _replication_task['ReplicationTasks'][0]['MigrationType']
                      _status = _replication_task['ReplicationTasks'][0]['Status']
                      print(_task)
                      print(_load_type)
                      print(_status)
                      if _load_type != 'full-load':
                          continue
                      if _status == 'ready':
                          response = client.start_replication_task(
                              ReplicationTaskArn=_task,
                              StartReplicationTaskType='start-replication'
                          )
                      elif _status == 'stopped':
                          response = client.start_replication_task(
                              ReplicationTaskArn=_task,
                              StartReplicationTaskType='reload-target'
                          )
                      else:
                          continue

                  return {
                      'statusCode': 200,
                      'body': json.dumps('StartReplicationTask Successfully!')
                  }

      FunctionName: !Ref LambdaDMSCronJobFunctionName
      Handler: index.lambda_handler
      Runtime: python3.8
      Timeout: 300
      Environment:
        Variables:
          dms_tasks: !Ref DMSTaskArn
      
  EventBridgeScheduledEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: Rules to filtering events
      Name: !Ref EventBridgeScheduledEventName
      ScheduleExpression: !Ref ScheduledTime
      Targets: 
        - Arn: !GetAtt LambdaDMSCronJob.Arn 
          Id: !Ref LambdaDMSCronJobFunctionName

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "LambdaDMSCronJobFunctionName"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EventBridgeScheduledEvent.Arn 